name: Dispatcher Integration CI

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
      mongo:
        image: mongo:6
        ports: ['27017:27017']
      redis:
        image: redis:7
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run integration tests
        env:
          RUN_INTEGRATION: '1'
        run: |
          if [ -d service-template ]; then
            cd service-template
            PYTHONPATH="$PWD" poetry run pytest tests/integration -q
          else
            echo "No template directory found; skipping integration tests."
          fi
