name: CI - BDD Policies

on:
  pull_request:
    paths:
      - 'src/**'
      - 'features/**'
      - 'tools/**'
      - 'pyproject.toml'

jobs:
  arch-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction
      - name: Run architecture check
        run: |
          python tools/arch_check.py
      - name: Run lockfile consistency check
        run: |
          python tools/lockfile_check.py
