name: CI - Lockfile helper

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  lockfile-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction
      - name: Run lockfile check
        id: lock
        run: |
          python tools/lockfile_check.py
      - name: Comment on PR if lockfile missing
        if: steps.lock.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Lockfile check failed: pyproject.toml changed but poetry.lock was not updated. Please run `poetry lock` locally and update the PR with the regenerated `poetry.lock`.'
            })
