version: '3.8'
services:
  mongo:
    image: mongo:6.0
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  user-service:
    build: .
    command: ["python", "-m", "uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=mongodb://root:example@mongo:27017/user_service_db
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
