apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hexa-monolith-rules
  labels:
    role: alert-rules
spec:
  groups:
    - name: hexa.rules
      rules:
        - alert: HighErrorRate
          expr: increase(http_requests_total{status=~"5.."}[5m]) > 5
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High 5xx error rate detected for hexa-monolith"
            description: "More than 5 server errors in the last 5m."
