apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  DATABASE_URL: "__DATABASE_URL__"
  JWT_SECRET: "__JWT_SECRET__"
  SENTRY_DSN: "__SENTRY_DSN__"

# Usage: replace placeholders with real values or generate from GitHub Actions
