name: Monolith CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-monolith:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y docker-compose-plugin
      - name: Start test services
        run: |
          cd monolith-template
          docker compose -f docker-compose.test.yml up -d
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Check poetry lock
        run: |
          cd monolith-template
          python scripts/check_poetry_lock.py
      - name: Install project deps
        run: |
          cd monolith-template
          poetry install --no-interaction
      - name: Run tests
        run: |
          cd monolith-template
          poetry run pytest -q
