name: Monolith enforcement

on:
  pull_request:
    branches: [ main ]

jobs:
  run-enforcement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-bdd redis httpx motor asyncpg

      - name: Run policy checks and tests
        env:
          PYTHONPATH: monolith-template
        run: |
          bash monolith-template/tools/run_tests.sh
