name: Postman smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  postman-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install fastapi uvicorn[standard] requests
      - name: Start test services (docker compose action)
        uses: docker/compose-action@v2
        with:
          files: monolith-template/docker-compose.test.yml
          args: up -d

      - name: Wait for services
        run: |
          # wait for Postgres
          for i in {1..30}; do docker exec monolith-template-postgres-1 pg_isready -U test && break || sleep 1; done
          # wait for redis
          for i in {1..30}; do docker exec monolith-template-redis-1 redis-cli ping && break || sleep 1; done
          # wait for mongo
          for i in {1..30}; do docker exec monolith-template-mongo-1 mongosh --eval 'db.runCommand({ping:1})' && break || sleep 1; done

      - name: Start app
        run: |
          cd monolith-template
          # ensure PYTHONPATH so `src` package is importable
          export PYTHONPATH=$PWD
          nohup python -m uvicorn src.app.main:app --host 0.0.0.0 --port 8000 &
          # wait for health
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:8000/health >/dev/null; then
              echo "up"
              break
            fi
            sleep 1
          done
      - name: Ensure app up
        run: |
          curl -sSf http://127.0.0.1:8000/health
      - name: Run smoke script
        run: |
          cd monolith-template
          python scripts/run_postman_smoke.py

      - name: Tear down test services
        if: always()
        uses: docker/compose-action@v2
        with:
          files: monolith-template/docker-compose.test.yml
          args: down
