name: Spec-Driven Implement

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spec-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate requirement metadata
        run: |
          python3 tools/requirement_validator.py
      - name: Run tests
        run: |
          cd service-template || exit 1
          if [ -f pyproject.toml ]; then
            poetry install --no-interaction
            poetry run pytest -q
          fi
      - name: Lockfile check
        run: |
          python3 tools/lockfile_check.py
